### ISSUE TITLE
Development Accuracy

### ISSUE THREAD

**Issue by mrdrozdov** [hshindo/POS-Tagging-benchmark#1]
Would you mind reporting the Development or Test accuracy that you were able to achieve with this model?

**Comment by hshindo** [comment]
For train and test set accuracy, see "POS-Tagging-benchmark/Merlin/result-embed_update.txt".

Roughly speaking, the test set accuracy is 97.3% on English WSJ, which is almost equivalent with Stanford POS-tagger.
